### ISSUE TITLE
Allow clusters to include other clusters and not just hosts

### ISSUE THREAD

**Issue by campbsb** [wouterdebie/i2cssh#114]
csshX allows tags/clusters to include other clusters which eases the management of large groups of servers. I would find it very useful for i2cssh to replicate this behaviour. We can implement it by adding in the following function and calling it from get_clusters_from_cluster_names() in place of config["clusters"][cluster_name]["hosts"]

```
def cluster_to_host_strings(cluster_name, config, cluster_names_done = None):
    """
    Given a cluster name, recursively convert any cluster entries
    in it to a host_string elements.
    """
    cluster_names_done = cluster_names_done or []
    if cluster_name in cluster_names_done:
        return []

    host_strings = []
    for cluster_or_host in config["clusters"][cluster_name]["hosts"]:
        if cluster_or_host in config["clusters"]:
            if cluster_or_host not in cluster_names_done and cluster_or_host != cluster_name:
                host_strings.extend(cluster_to_host_strings(cluster_or_host, config, cluster_names_done))
                cluster_names_done.append(cluster_or_host)
        else:
            host_strings.append(cluster_or_host)

    return host_strings
```

**Comment by wouterdebie** [comment]
I like the idea, but what should the grouping for tabs be in case we specify `-t` or `-T`? Do the included clusters get their own tab or are all hosts just included in the list of hosts (as per your example)? Do we just want to include the hosts from the other cluster, or do we want to respect the cluster options (like login, shell, etc) from the included cluster as well?

**Comment by campbsb** [comment]
If we start to consider options or tab groupings for included clusters, the complexity spirals out of control. Also, you would most likely only want the superset options. For example, the rows & columns specifications of a sub-cluster should not be applied to the superset!

Also, this will then give you the ability to apply different sets of settings against the same hosts by having multiple super-clusters including the same sub-cluster.

**Comment by wouterdebie** [comment]
Exactly. So what we could do (as your PR does) is to just include the hosts of a different cluster and don't worry about the settings of the other cluster. I kind of like that idea, because that basically gives you the opportunity to connect to a group of hosts in different ways (different login, different shell, etc).

I will add a different header in the config (like `include_hosts_from_cluster`) or something, to make the configuration explicit, rather than having "special" hosts that are actually clusters. I'll not make this recursive for now, since the user has the opportunity to explicitly add one or more clusters.

**Comment by wouterdebie** [comment]
I've uploaded version 0.0.11 that has the option `include_from`. This is only enabled as a parameter in the config file. Let me know what you think.

**Comment by campbsb** [comment]
I'm happy with the include_from keyword, although I'm not personally inclined to cater for people who use the same name for a cluster as they do for a hostname!

One small fix to allow for a cluster to not have a hosts section:
```
382c382
<         host_strings = config["clusters"][cluster_name].get("hosts", [])
---
>         host_strings = config["clusters"][cluster_name]["hosts"]
```
