### ISSUE TITLE
Login string with username@host@gateway

### ISSUE THREAD

**Issue by damientkk** [wouterdebie/i2cssh#115]
With the new release of i2cssh version 0.0.9, the login string for my cluster hosts specified in .i2csshrc no longer works.

The entry in my cluster looks something like this:

(userid)@(hostname)@(Pass through host) 

Can you advise if there is any workaround or usage of flags that could help. I wasn't able to resolve the issue using the -g flag

Errors stack:
Traceback (most recent call last):
  File "/usr/local/bin/i2cssh", line 458, in <module>
    main()
  File "/usr/local/bin/i2cssh", line 454, in main
    i2cssh(prog_name="i2cssh")
  File "/usr/local/Cellar/i2cssh/0.0.9/libexec/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/i2cssh/0.0.9/libexec/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/i2cssh/0.0.9/libexec/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/i2cssh/0.0.9/libexec/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/bin/i2cssh", line 95, in i2cssh
    clusters = get_clusters_from_cluster_names(
  File "/usr/local/bin/i2cssh", line 381, in get_clusters_from_cluster_names
    hosts = host_strings_to_hosts(host_strings)
  File "/usr/local/bin/i2cssh", line 394, in host_strings_to_hosts
    (login, hostname) = parse_hostname(host_string)
  File "/usr/local/bin/i2cssh", line 418, in parse_hostname
    login, host = hostname.split("@")
ValueError: too many values to unpack (expected 2)

Thanks.

**Comment by wouterdebie** [comment]
Interesting! This probably unintentionally worked in older (Ruby) versions and from just seeing this, I don't know why. What do you expect to happen exactly? I'll investigate and will get back to you.

**Comment by damientkk** [comment]
Hi Wouter,

It looks like the code is failing here:

def parse_hostname(hostname):
    """Parse a [login@]hostname and return a tuple of (login, host)"""
    login = None
    host = hostname
    if "@" in hostname:
        login, host = hostname.split("@")
    return login, host

For my use case, I actually need to specify a "jump/audit" host in order to
get to the target host hence the format of below entry in the .i2csshrc

  clusterA:
    hosts:
      - ***@***.******@***.***_host
      - ***@***.******@***.***_host
      - ***@***.******@***.***_host

Below is my syntax for invoking the cluster defined
i2cssh -b -XA -XY -c clusterA

Thanks for your time.

Cheers,
Damien

**Comment by damientkk** [comment]
Hi Wouter,

Do you have any update on the error.

Thanks,
Damien

**Comment by wouterdebie** [comment]
@damientkk I've just uploaded version 0.0.12, which has this fix. Let me know if this solves your issue. From reading your description it seems that you just need to be able to have an `@` in the username, since the host you connect to requires that, right? I've added this use case (which makes sense). If something else is required (like automatically parsing out the jump host for `-g`), let me know.

**Comment by damientkk** [comment]
Version 0.0.12 has resolved the issue of specifying an additional jump host
! However, the profile option with -p appears to be broken. Using the
following syntax "i2cssh -b -p Prod -XA -XY -c clusterA", the Prod profile
for the windows (e.g Green background) shows up briefly before resetting to
the default terminal settings when connections to the various hosts have
been established. Any idea why that might be the case?
