### ISSUE TITLE
How to type commands specific to 1 ip during broadcast 

### ISSUE THREAD

**Issue by erdarun** [wouterdebie/i2cssh#116]
Im using broadcast to multiple IP's, I can fire same command to all broadcast ip's but how to run particular 1 command to specific ip window during broadcast mode?

Use case is like during broadcast mode just want to run particular command just in 1 IP to know status

**Comment by wouterdebie** [comment]
You can toggle broadcast mode off and on with alt-shift-cmd-I and shift-cmd-I. Is that what you need?

<img width="697" alt="image" src="https://user-images.githubusercontent.com/172038/214756242-147a32d7-7229-4d3b-bb04-65ddcb106912.png">
