### ISSUE TITLE
AWS Multi Pem Cluster

### ISSUE THREAD

**Issue by MuratKaragozgil** [wouterdebie/i2cssh#121]
Hello,

I have a question.

I have a lot of servers in different regions on AWS. So my connections commands like this.

1. alias capinv6="ssh -i '/Users/murat/Downloads/x.pem' ubuntu@35.180.999.99"
2. alias capinv7="ssh -i '/Users/murat/Downloads/x.pem' ubuntu@13.39.999.99"
3. alias capinv5="ssh -i '/Users/murat/Downloads/y.pem' ubuntu@13.39.999.99"
4. alias capinv4="ssh -i '/Users/murat/Downloads/y.pem' ubuntu@52.47.999.99"
5. alias capinv3="ssh -i '/Users/murat/Downloads/z.pem' ubuntu@18.197.999.99"
6. alias capinv2="ssh -i '/Users/murat/Downloads/z.pem' ubuntu@3.71.999.99"
7. alias capinv1="ssh -i '/Users/murat/Downloads/z.pem' ubuntu@3.75.999.99"

How can I create a cluster to open these connections with a single command?

Thanks for your help,
Murat

**Comment by wouterdebie** [comment]
Even though there's an `extra` option in i2cssh you can use to set the priv key (`-Xi=x.pem` or `-Xi=y.pem`, etc), this doesn't apply to hosts, but only to global options or per cluster. In your case I'd use your ssh config file (`~/.ssh/config`) and add different `IdentityFile`s for each host (or subnet). In your case you'd have something like:

```
Host 35.180.999.99
  User ubuntu
  IdentityFile /Users/murat/Downloads/x.pem

Host 13.39.999.99
  User ubuntu 
  IdentityFile /Users/murat/Downloads/y.pem
```

And if your identity files map to different subnets, you can even fo something like 
```
Host 13.39.*
  User ubuntu
  IdentityFile /Users/murat/Downloads/y.pem
```

For the i2ssh config you would just do:
```
version: 2
clusters:
  mycluster:
    hosts:
      - 35.180.999.99
      - 13.39.999.99
      - 52.47.999.99
      - ...
```

**Comment by wouterdebie** [comment]
Also, thank you for the question, because I found a bug with parsing the `extra` from the config file :)

**Comment by MuratKaragozgil** [comment]
Thank you very much 🚀

**Comment by wouterdebie** [comment]
My pleasure!
