### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by kundan1974** [wouterdebie/i2cssh#126]
**Describe the bug**
This is installation issue
I am using MacBook Pro
Apple M2 Chip running Ventura 13.4.1 (c)

And when installing using  brew install wouterdebie/repo/i2csshr
I am getting this error

Last 15 lines from /Users/chufal/Library/Logs/Homebrew/i2cssh/06.pip:

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /opt/homebrew/Cellar/i2cssh/0.0.18/libexec/bin/python3.11 /opt/homebrew/Cellar/i2cssh/0.0.18/libexec/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py get_requires_for_build_wheel /private/tmp/tmp45kot8ne
  cwd: /private/tmp/i2cssh--PyYAML-20230721-69058-1nsfvzk/PyYAML-6.0
  Getting requirements to build wheel: finished with status 'error'
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip is available: 23.0.1 -> 23.2
[notice] To update, run: python3.11 -m pip install --upgrade pip

**Comment by wouterdebie** [comment]
Fixed in #70
