### ISSUE TITLE
Use exec to save dropping back into local bash shell.

### ISSUE THREAD

**Issue by campbsb** [wouterdebie/i2cssh#127]
https://github.com/wouterdebie/i2cssh/blob/7e209abc95f0504abaf9654a4a47ee73eab4a918/i2cssh#L272

If you exec the ssh, then windows will close automatically without dropping you back into a local bash shell. Eg:

```
                        await pane.async_send_text(f"unset HISTFILE && exec {ssh_prefix} {send_env} {host}\n")
```
Saves you having to hit Ctrl-D twice.

Just a suggestion...

**Comment by wouterdebie** [comment]
Nice suggestion! The only thing is that you'll not see any errors if they happen and ssh gets terminated. I think I'll make it an option you can toggle.

**Comment by campbsb** [comment]
Even better :-)

**Comment by wouterdebie** [comment]
Interesting. I'm not sure what to do about that though..

**Comment by campbsb** [comment]
I've raised an issue against iTerm2 (see URL in the comment), and here's a workaround:

```
diff --git a/i2cssh b/i2cssh.orig
index 8727d7e..c71db64 100755
--- a/i2cssh
+++ b/i2cssh.orig
@@ -267,9 +267,7 @@ def exec_in_iterm(groups, opts):
                                                        host_opts.get("gateway"))

                         if host_opts.get("exec"):
-                            # Set ControlMaster=no as a workaround for
-                            # https://gitlab.com/gnachman/iterm2/-/issues/11032
-                            ssh_prefix = f"exec {ssh_prefix} -o ControlMaster=no"
+                            ssh_prefix = f"exec {ssh_prefix}"

                         if s := host_opts.get("sleep"):
                             await asyncio.sleep(s)
```

**Comment by wouterdebie** [comment]
@campbsb cool! I've added this to 0.0.20. Mind keeping track of this issue for me, so we can revert if this is fixed in iTerm2?

**Comment by campbsb** [comment]
Sure thing!
