### ISSUE TITLE
Question: How to break out of broadcast to focus keyboard on one host

### ISSUE THREAD

**Issue by ppi-agray** [wouterdebie/i2cssh#132]
Let say I run:
`i2cssh -b -m host1,host2,host3`
If I type in one window, it goes to all hosts. Great!

But now let's say I want to focus the keyboard on just host1.
I fix whatever I need to fix on host1 and now I want to go back to typing to all hosts.

How do I toggle the sending-the-keyboard to either 1 host or all hosts?
Thanks! Awesome tool!

**Comment by wouterdebie** [comment]
Hi! You can hit Cmd-shift-i to toggle broadcast, or in the iterm2 menu Shell -> Broadcast input.

<img width="721" alt="image" src="https://github.com/wouterdebie/i2cssh/assets/172038/fd35945f-04ea-4c1a-b771-2af289aa4599">

**Comment by ppi-agray** [comment]
@wouterdebie , you rock! Thanks!!!
