### ISSUE TITLE
can't connect to cluster through jump host

### ISSUE THREAD

**Issue by dircadmin** [wouterdebie/i2cssh#145]
Hi, I'm not very good at this, but I'm trying hard to use a single private key to connect to a Custer through a jump host. The single connections to each of them work. 
Could it be possible to get an example on how to set this up?

**Comment by wouterdebie** [comment]
You should be able to do something like this:

```
i2cssh -A -g user@jumphost myuser@host1 myuser@host2 myuser@host3
```

or 
```
i2cssh -A -g user@jumphost clustername
```

**Comment by dircadmin** [comment]
Thanks a lot @wouterdebie 
I can use: i2cssh -W -Xto=IdentityFile=.ssh/id__rsa -A -g user@jumphost clustername
And it works for the cluster, but is there a way to also connect to the jumphost with the same ssh-key?

**Comment by dircadmin** [comment]
OK, I found the solution: 
i2cssh -W -Xto=IdentityFile=.ssh/id_rsa -A -g "-i .ssh/id_rsa user@jumphost" clustername

This will be a big help. Thank you so much for this great Tool!
