### ISSUE TITLE
i2cssh is broken without a config file

### ISSUE THREAD

**Issue by dustyleary** [wouterdebie/i2cssh#17]
If there is no ~/.i2csshrc, then i2cssh just doesn't work, with a stacktrace instead of an error message:

$ i2cssh root@HOSTNAME1 root@HOSTNAME2
/Library/Ruby/Gems/1.8/gems/i2cssh-1.8.0/lib/i2cssh.rb:62:in `split_session': undefined method`[]' for nil:NilClass (NoMethodError)
    from /Library/Ruby/Gems/1.8/gems/i2cssh-1.8.0/lib/i2cssh.rb:25:in `initialize'
    from /Library/Ruby/Gems/1.8/gems/i2cssh-1.8.0/bin/i2cssh:191:in`new'
    from /Library/Ruby/Gems/1.8/gems/i2cssh-1.8.0/bin/i2cssh:191
    from /usr/bin/i2cssh:23:in `load'
    from /usr/bin/i2cssh:23

**Comment by carenas** [comment]
FWIW I couldn't reproduce this either running the current HEAD in macOS 10.12.6 (ruby 2.0)
