### ISSUE TITLE
[Req] Ability to open in new tab

### ISSUE THREAD

**Issue by XL64** [wouterdebie/i2cssh#21]
Hello,

What would be great is to open i2ssh shells in a new tab.
(I never remember how to switch window ^^)
Really not a high priority request, just a suggestion.

XL.

**Comment by queimadus** [comment]
:+1: +1

**Comment by RawTech** [comment]
+1 Would like to see this implemented. Would result in a cleaner workspace.

**Comment by tflhyl** [comment]
👍 would love to see this as well

**Comment by Programie** [comment]
👍 +1
