### ISSUE TITLE
appscript gem causing errors

### ISSUE THREAD

**Issue by davidxia** [wouterdebie/i2cssh#23]
$ i2cssh -m host1.com,host2.com

    /Library/Ruby/Gems/1.8/gems/rb-appscript-0.6.1/lib/appscript.rb:542:in `_send_command': CommandError (Appscript::CommandError)
        OSERROR: -1719
        MESSAGE: Access for assistive devices is disabled.
        OFFENDING OBJECT: app("/System/Library/CoreServices/System Events.app").processes["iTerm"].menu_bars[1]
        COMMAND: app("/System/Library/CoreServices/System Events.app").processes["iTerm"].menu_bars[1].menu_bar_items["Shell"].menus["Shell"].menu_items["Split Vertically with Current Profile"].click()
      from /Library/Ruby/Gems/1.8/gems/rb-appscript-0.6.1/lib/appscript.rb:642:in `method_missing'
      from /Library/Ruby/Gems/1.8/gems/i2cssh-1.9.0/lib/i2cssh.rb:74:in `split_session'
      from /Library/Ruby/Gems/1.8/gems/i2cssh-1.9.0/lib/i2cssh.rb:73:in `upto'
      from /Library/Ruby/Gems/1.8/gems/i2cssh-1.9.0/lib/i2cssh.rb:73:in `split_session'
      from /Library/Ruby/Gems/1.8/gems/i2cssh-1.9.0/lib/i2cssh.rb:28:in `initialize'
      from /Library/Ruby/Gems/1.8/gems/i2cssh-1.9.0/bin/i2cssh:192:in `new'
      from /Library/Ruby/Gems/1.8/gems/i2cssh-1.9.0/bin/i2cssh:192
      from /usr/bin/i2cssh:19:in `load'
      from /usr/bin/i2cssh:19

    $ ruby -v
    ruby 1.8.7 (2012-02-08 patchlevel 358) [universal-darwin11.0]

**Comment by MelonSmasher** [comment]
same issue here OSX 10.10.3 :

```
melon@odin:~$ i2cssh -c cloudweb -l root
/Users/melon/.rvm/gems/ruby-2.1.5/extensions/x86_64-darwin-14/2.1.0-static/rb-appscript-0.6.1/appscript.rb:542:in `_send_command': CommandError (Appscript::CommandError)
		OSERROR: -1728
		MESSAGE: Can't get reference.
		OFFENDING OBJECT: app("/System/Library/CoreServices/System Events.app").processes["/opt/homebrew-cask/Caskroom/iterm2/2.0/iTerm.app"]
		COMMAND: app("/System/Library/CoreServices/System Events.app").processes["/opt/homebrew-cask/Caskroom/iterm2/2.0/iTerm.app"].menu_bars[1].menu_bar_items["Shell"].menus["Shell"].menu_items["Split Vertically with Current Profile"].click()
	from /Users/melon/.rvm/gems/ruby-2.1.5/extensions/x86_64-darwin-14/2.1.0-static/rb-appscript-0.6.1/appscript.rb:642:in `method_missing'
	from /Users/melon/.rvm/gems/ruby-2.1.5/gems/i2cssh-1.13.2/lib/i2cssh.rb:117:in `block in split_session'
	from /Users/melon/.rvm/gems/ruby-2.1.5/gems/i2cssh-1.13.2/lib/i2cssh.rb:116:in `upto'
	from /Users/melon/.rvm/gems/ruby-2.1.5/gems/i2cssh-1.13.2/lib/i2cssh.rb:116:in `split_session'
	from /Users/melon/.rvm/gems/ruby-2.1.5/gems/i2cssh-1.13.2/lib/i2cssh.rb:30:in `initialize'
	from /Users/melon/.rvm/gems/ruby-2.1.5/gems/i2cssh-1.13.2/bin/i2cssh:290:in `new'
	from /Users/melon/.rvm/gems/ruby-2.1.5/gems/i2cssh-1.13.2/bin/i2cssh:290:in `<top (required)>'
	from /Users/melon/.rvm/gems/ruby-2.1.5/bin/i2cssh:23:in `load'
	from /Users/melon/.rvm/gems/ruby-2.1.5/bin/i2cssh:23:in `<main>'
	from /Users/melon/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
	from /Users/melon/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
melon@odin:~$ ruby -v
ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin14.0]
```

**Comment by inventionlabsSydney** [comment]
Hey guys,
just a heads up, if you want to fix this enable Iterm to have access to assistive devices :+1: 
https://support.apple.com/en-au/HT202866
