### ISSUE TITLE
Yosemite issue.  Please help!

### ISSUE THREAD

**Issue by purduemike** [wouterdebie/i2cssh#33]
Just converted to OSX Yosemite and this is what is get. I've tried uninstalling and reinstalling with gem, brew update, nothing works.  Thanks!

i2cssh -l root server1 server2
/usr/local/lib/ruby/gems/2.1.0/extensions/x86_64-darwin-13/2.1.0/rb-appscript-0.6.1/_aem/connect.rb:89:in `rescue in launch_application': OS error (-600) (Connect::CantLaunchApplicationError)
    from /usr/local/lib/ruby/gems/2.1.0/extensions/x86_64-darwin-13/2.1.0/rb-appscript-0.6.1/_aem/connect.rb:85:in`launch_application'
    from /usr/local/lib/ruby/gems/2.1.0/extensions/x86_64-darwin-13/2.1.0/rb-appscript-0.6.1/_aem/connect.rb:182:in `rescue in local_app'
    from /usr/local/lib/ruby/gems/2.1.0/extensions/x86_64-darwin-13/2.1.0/rb-appscript-0.6.1/_aem/connect.rb:177:in`local_app'
    from /usr/local/lib/ruby/gems/2.1.0/extensions/x86_64-darwin-13/2.1.0/rb-appscript-0.6.1/aem.rb:146:in `by_path'
    from /usr/local/lib/ruby/gems/2.1.0/extensions/x86_64-darwin-13/2.1.0/rb-appscript-0.6.1/appscript.rb:57:in`connect'
    from /usr/local/lib/ruby/gems/2.1.0/extensions/x86_64-darwin-13/2.1.0/rb-appscript-0.6.1/appscript.rb:159:in `reference_by_name'
    from /usr/local/lib/ruby/gems/2.1.0/extensions/x86_64-darwin-13/2.1.0/rb-appscript-0.6.1/appscript.rb:633:in`method_missing'
    from /usr/local/lib/ruby/gems/2.1.0/gems/i2cssh-1.12.0/lib/i2cssh.rb:18:in `initialize'
    from /usr/local/lib/ruby/gems/2.1.0/gems/i2cssh-1.12.0/bin/i2cssh:192:in`new'
    from /usr/local/lib/ruby/gems/2.1.0/gems/i2cssh-1.12.0/bin/i2cssh:192:in `<top (required)>'
    from /usr/local/bin/i2cssh:23:in`load'
    from /usr/local/bin/i2cssh:23:in `<main>'

**Comment by johntdyer** [comment]
I am also unable to run on Yosemite

my config

```yaml
---
version: 2
itermname: /opt/homebrew-cask/Caskroom/iterm2/2.0.0/iTerm.app
clusters:
  prod:
    login: jdyer
    hosts:
     - t108.orl.xxx
     - t109.orl.xxx

```

and here is the error 

```
# jdyer at retina.dyer in ~ [9:43:33]
$ i2cssh prod
/Users/jdyer/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/extensions/x86_64-darwin-14/2.1.0-static/rb-appscript-0.6.1/appscript.rb:542:in `_send_command': CommandError (Appscript::CommandError)
		OSERROR: -1728
		MESSAGE: Can't get reference.
		OFFENDING OBJECT: app("/System/Library/CoreServices/System Events.app").processes["/opt/homebrew-cask/Caskroom/iterm2/2.0.0/iTerm.app"]
		COMMAND: app("/System/Library/CoreServices/System Events.app").processes["/opt/homebrew-cask/Caskroom/iterm2/2.0.0/iTerm.app"].menu_bars[1].menu_bar_items["Shell"].menus["Shell"].menu_items["Split Vertically with Current Profile"].click()
	from /Users/jdyer/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/extensions/x86_64-darwin-14/2.1.0-static/rb-appscript-0.6.1/appscript.rb:642:in `method_missing'
	from /Users/jdyer/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/i2cssh-1.12.0/lib/i2cssh.rb:91:in `block in split_session'
	from /Users/jdyer/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/i2cssh-1.12.0/lib/i2cssh.rb:90:in `upto'
	from /Users/jdyer/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/i2cssh-1.12.0/lib/i2cssh.rb:90:in `split_session'
	from /Users/jdyer/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/i2cssh-1.12.0/lib/i2cssh.rb:29:in `initialize'
	from /Users/jdyer/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/i2cssh-1.12.0/bin/i2cssh:192:in `new'
	from /Users/jdyer/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/i2cssh-1.12.0/bin/i2cssh:192:in `<top (required)>'
	from /Users/jdyer/.rbenv/versions/2.1.3/bin/i2cssh:23:in `load'
	from /Users/jdyer/.rbenv/versions/2.1.3/bin/i2cssh:23:in `<main>'

# jdyer at retina.dyer in ~ [9:43:39]
```

I am running OSX 10.10.1 and iTerm2 Build 2.0.0.20141103
