### ISSUE TITLE
Do not show "UNUSED" window

### ISSUE THREAD

**Issue by jolexa** [wouterdebie/i2cssh#35]
Hi,
Is it possible to not show the unused window when the cluster has an 'odd' number? I don't care if it creates a non symmetrical set.

Thanks.

**Comment by TJM** [comment]
It also happens on even sets... for example, with 10, I get 2 labeled "cat" with "UNUSED" in red text in the window.

https://www.dropbox.com/s/n2vwndkx2d3wgoj/Screenshot%202016-02-23%2017.07.51.png?dl=0
