### ISSUE TITLE
--clusters option only connecting to 3 hosts

### ISSUE THREAD

**Issue by devopsprosiva** [wouterdebie/i2cssh#42]
Hi,

When I use "--clusters cluster1,cluster2,cluster3", only 3 hosts are being connected. In the other host tabs, it says "UNUSED".

Siva

**Comment by wouterdebie** [comment]
How did you configure your clusters? Can you paste you config?

**Comment by lensen** [comment]
I have a similar issue with 2.2.0 except that it connects to all hosts in the first 2 clusters, but any more clusters and it opens UNUSED panels for those hosts (the amount of split panels is correct btw).
