### ISSUE TITLE
Replace rb-appscript with rb-scpt?

### ISSUE THREAD

**Issue by mmindenhall** [wouterdebie/i2cssh#46]
Hello,

There's a discussion [here](https://github.com/mattneub/appscript/issues/12) about the rb-appscript gem problems.  In that thread, there's mention of a fork of the rb-appscript project that was done in pure ruby -- https://github.com/BrendanThompson/rb-scpt.

Could the `rb-scpt` gem be used to restore compatibility with the most recent versions of ruby?

**Comment by wouterdebie** [comment]
Yeah, I think that makes sense. As far as I can see from the thread, this is compatible with ruby >2.0.0. I think we can deprecate anything less than that. 
It also seems that rb-scpt is API compatible with rb-appscript, but I haven't been able to try it out. Would you be able to do this?
