### ISSUE TITLE
Problem with iTerm2 2.9.20160206

### ISSUE THREAD

**Issue by testn** [wouterdebie/i2cssh#49]
I just installed it on Mac with iterm2 2.9.20160206 but got the following exception

```
i2cssh -m server1, server2
/Library/Ruby/Gems/2.0.0/gems/rb-scpt-1.0.1/lib/rb-scpt.rb:676:in `rescue in method_missing': Unknown property, element or command: 'create_window_with_profile' (RuntimeError)
    from /Library/Ruby/Gems/2.0.0/gems/rb-scpt-1.0.1/lib/rb-scpt.rb:646:in `method_missing'
    from /Library/Ruby/Gems/2.0.0/gems/i2cssh-2.0.0/lib/i2cssh.rb:20:in `initialize'
    from /Library/Ruby/Gems/2.0.0/gems/i2cssh-2.0.0/bin/i2cssh:298:in `new'
    from /Library/Ruby/Gems/2.0.0/gems/i2cssh-2.0.0/bin/i2cssh:298:in `<top (required)>'
    from /usr/local/bin/i2cssh:23:in `load'
    from /usr/local/bin/i2cssh:23:in `<main>'
```

**Comment by wouterdebie** [comment]
What ruby version are you using? What version of i2cssh are you running?

**Comment by testn** [comment]
```
ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]
i2cssh-2.0.0
```

**Comment by wouterdebie** [comment]
Strange.. does the i2cssh 1.6 work for you?

**Comment by elmalto** [comment]
Same issue here. Tried 2.0 and 1.6.0

**Comment by testn** [comment]
same problem with iTerm2 2.9.20160313

**Comment by kibitan** [comment]
Same issue, iTerm 2.1.4 , ruby 2.2.3

**Comment by 33b5e5** [comment]
Same. iTerm 2 Build 2.1.4, ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]

**Comment by sharpyy** [comment]
Same.  iTerm 2 Build 2.1.4 .  - RUBY VERSION: 2.1.5 (2014-11-13 patchlevel 273) [x86_64-darwin14.0]

**Comment by amcnerlin** [comment]
Same. iTerm 2 Build 2.1.4, ruby 1.9.3p551 (2014-11-13 revision 48407) [x86_64-darwin14.5.0]

**Comment by wouterdebie** [comment]
Thanks for all the feedback. I'm having a hard time reproducing this so debugging is hard.. I'll see what I can do.

**Comment by testn** [comment]
should this line

`@iterm = Appscript.app.by_name("iTerm")`

refer to iTerm2 instead?

**Comment by amcnerlin** [comment]
I got it to work by upgrading iTerm2 to 2.9.20160313 (beta)

I'm using ruby-1.9.3-p551

@testn iTerm2 v2.9 should have the application name "iTerm" not "iTerm2".  If you extracted the zip for 2.9 and the file iTerm already existed then it will be extracted as iTerm2.  Just rename it to iTerm, put it in the Applications folder (overwriting the earlier version) and try again. 

This worked for me

**Comment by testn** [comment]
@amcnerlin that works!

**Comment by kibitan** [comment]
@amcnerlint i install `iterm2-beta` by `brew cask` and it works!
