### ISSUE TITLE
Problems with fullscreen (-f / -fullscreen)

### ISSUE THREAD

**Issue by CyberDK** [wouterdebie/i2cssh#52]
Hello,

After upgrading to Iterm2 3.0 and I2cssh 2.0 the fullscreen options seems to be broken. 

I have tried both options
i2cssh --fullscreen -nb -Xp=9090 Servers
or 
i2cssh -F -nb -Xp=9090 Servers

We did a workaround on this just by creating a new Iterm2 profile and set the "Window" -> "Style" mode to Fullscreen and added the profile information to .i2csshrc 

![screen shot 2016-06-08 at 10 48 51 am](https://cloud.githubusercontent.com/assets/13014190/15893988/7f82e9b2-2d83-11e6-8aca-330ed14a12a2.png)

BTW Create product using it everyday ;)

**Comment by brando56894** [comment]
Yea the -F flag doesn't work for me either.
