### ISSUE TITLE
i2cssh + iterm2 not working on macos Sierra

### ISSUE THREAD

**Issue by acomisario** [wouterdebie/i2cssh#59]
Using -2, --iterm2 or -i iTerm2 gives the same error:

Alejandros-MBP:~ alejandrito$ i2cssh -2 -m user1@host1,user2@host2 -m user3@host3 user4@host4 user5@host5
**/Library/Ruby/Gems/2.0.0/gems/rb-scpt-1.0.1/lib/_aem/findapp.rb:30:in `rescue in _find_app': Application "[\"iTerm.app\"]" not found. (FindApp::ApplicationNotFoundError)**
    from /Library/Ruby/Gems/2.0.0/gems/rb-scpt-1.0.1/lib/_aem/findapp.rb:25:in `_find_app'
    from /Library/Ruby/Gems/2.0.0/gems/rb-scpt-1.0.1/lib/_aem/findapp.rb:55:in`rescue in by_name'
    from /Library/Ruby/Gems/2.0.0/gems/rb-scpt-1.0.1/lib/_aem/findapp.rb:49:in `by_name'
    from /Library/Ruby/Gems/2.0.0/gems/rb-scpt-1.0.1/lib/rb-scpt.rb:855:in`by_name'
    from /Library/Ruby/Gems/2.0.0/gems/rb-scpt-1.0.1/lib/rb-scpt.rb:932:in `by_name'
    from /Library/Ruby/Gems/2.0.0/gems/i2cssh-2.2.0/lib/i2cssh.rb:13:in`initialize'
    from /Library/Ruby/Gems/2.0.0/gems/i2cssh-2.2.0/bin/i2cssh:298:in `new'
    from /Library/Ruby/Gems/2.0.0/gems/i2cssh-2.2.0/bin/i2cssh:298:in`<top (required)>'
    from /usr/local/bin/i2cssh:23:in `load'
    from /usr/local/bin/i2cssh:23:in`<main>'

**Comment by charliwest** [comment]
Yep, same here

**Comment by dallinwright** [comment]
Same, here is the error message.

in `_send_command': CommandError (Appscript::CommandError)
                OSERROR: 1
                MESSAGE: No profile exists named 'Default'
                COMMAND: app("/Applications/iTerm.app").create_window_with_profile("Default", {:command=>"/usr/bin/env bash -l"})

**Comment by ashokrajar** [comment]
+1 same issue.

**Comment by ashokrajar** [comment]
My little hack - 
I made a duplicate of iTerm2.app and renamed to iTerm.app and it seems to work for now.

**Comment by ashokrajar** [comment]
Looks like the real problem is with this module => https://github.com/BrendanThompson/rb-scpt which is internally used by i2cssh for finding apps and it's not active for more than a year now.

**Comment by acomisario** [comment]
ok, so ... i think this can be closed since it can be wrokarounded

**Comment by anquegi** [comment]
Hi, I cannot also start i2cssh, and and my iterm2 is allready called iterm, what should I do?

**Comment by akki** [comment]
In my case, I had to duplicate the `iTerm` app and rename it to `iTerm2` in the `Applications` folder.
