### ISSUE TITLE
How to broadcast command?

### ISSUE THREAD

**Issue by didip** [wouterdebie/i2cssh#64]
Sorry for asking what's probably the most trivial question.

How can I broadcast command? This is the i2cssh command I do:

```
i2cssh -l myself hostA hostB hostC
```

**Comment by Inanias** [comment]
> -b, --broadcast
>Enable broadcast on startup. i2cssh will send cmd-shift-i to the window and press the OK button.

press cmd-shift-i or use -b
`i2cssh -l myself hostA hostB hostC -b`
