### ISSUE TITLE
Delay Login In RC File

### ISSUE THREAD

**Issue by brando56894** [wouterdebie/i2cssh#77]
I've looked around and can't find anywhere mentioning if the **sleep** flag (-s) is able to be used in the .i2csshrc file, I tried to add **sleep:1** under the **hosts:** line but that just caused i2cssh to crash upon execution.

One of my clusters has 25 hosts in it and when I shell into them all at once it overloads our LDAP server and denies a few connections, so I have to manually reconnect to them. If I can delay it by like half a second or a second this should prevent that from happening.

**Comment by chrisagiddings** [comment]
+1
