### ISSUE TITLE
StrictHostKeyChecking option does not work

### ISSUE THREAD

**Issue by mrshpaks** [wouterdebie/i2cssh#79]
Hi there.

Just tried to add StrictHostKeyChecking=no option to command and it did not work

```
i2cssh -l <username> -Xi=<key path> -Xo=StrictHostKeyChecking=no -m <instance list>
```
Got output like below:
```
unset HISTFILE && echo -e "\033]50;SetProfile=Default\a" && 
ssh -i <key> -o StrictHostKeyChecking no  <user>@<host IP>

command-line line 0: missing argument.
```
Looks like it's escaping = sign.

**Comment by ashishchandra1** [comment]
I am having the same issue, wonder there is a way that we can take of it/

**Comment by Programie** [comment]
I have the same issue.

My current workaround is to use a separate ssh config file where I specify the SSH options I want to use for i2cssh using `-XF=/path/to/config`.

**Comment by dabrady** [comment]
@wouterdebie I've created a bugfix PR to address this issue: https://github.com/wouterdebie/i2cssh/pull/96

Please have a look when you have time! 😄
