### ISSUE TITLE
i2cssh is not evenly splitting the pane

### ISSUE THREAD

**Issue by msanath** [wouterdebie/i2cssh#82]
All the panes get loaded as multiple rows in the same column. Using MacOs Sierra. 
Any suggestions?

**Comment by joelsdc** [comment]
That happens to me when I move or touch the iTerm windows while they are loading.

If you open the i2cssh and let it load completely before moving the focus to another window, does that work?

**Comment by msanath** [comment]
Nope. It does not work.

**Comment by joelsdc** [comment]
What versions do you have? 

I'm on:

$ gem list | grep i2cssh
i2cssh (2.2.0)
$

$ gem -v
2.7.6
$ ruby -v
ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin16]
$

macOS Sierra 10.12.6

**Comment by msanath** [comment]
I was on an older version of ruby. Upgraded it and ran into https://github.com/wouterdebie/i2cssh/issues/83 :-|

**Comment by joelsdc** [comment]
Yeah... I opened that one. I have it working on v2.4.2 (as #81 complains about v2.4.3)....

Give it a try, using `rvm` it's easy to manage multiple ruby versions.

**Comment by msanath** [comment]
That worked! thanks!
