### ISSUE TITLE
i2cssh fails on Mojave 

### ISSUE THREAD

**Issue by batic** [wouterdebie/i2cssh#85]
Any ideas?

Might not be related to just Mojave, but I have no clue as I've never used i2cssh before.

```
/Library/Ruby/Gems/2.3.0/gems/rb-scpt-1.0.3/lib/rb-scpt.rb:542:in` `_send_command': CommandError (Appscript::CommandError)
		OSERROR: -1743
		COMMAND: app("/Users/user/Applications/iTerm.app").create_window_with_profile("Default", {:command=>"/usr/bin/env bash -l"})
	from /Library/Ruby/Gems/2.3.0/gems/rb-scpt-1.0.3/lib/rb-scpt.rb:642:in `method_missing'
	from /Library/Ruby/Gems/2.3.0/gems/i2cssh-2.2.0/lib/i2cssh.rb:21:in `initialize'
	from /Library/Ruby/Gems/2.3.0/gems/i2cssh-2.2.0/bin/i2cssh:298:in `new'
	from /Library/Ruby/Gems/2.3.0/gems/i2cssh-2.2.0/bin/i2cssh:298:in `<top (required)>'
	from /usr/local/bin/i2cssh:22:in `load'
	from /usr/local/bin/i2cssh:22:in `<main>
'```

**Comment by nynhex** [comment]
Try bumping ruby.  I'm on a Mojave build and am `2.5.1` with latest i2cssh and it works fine.

**Comment by adrianthedev** [comment]
I tried 2.5.1 and it's not working. Also, it's just a Mojave thing I used 2.2.2 before (because I use other apps with this version) and worked fine.

Maybe it's an iTerm issue?

I'll paste my output here as well.

```
Traceback (most recent call last):
	13: from /Users/adrian/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `<main>'
	12: from /Users/adrian/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `eval'
	11: from /Users/adrian/.rvm/gems/ruby-2.5.1/bin/i2cssh:23:in `<main>'
	10: from /Users/adrian/.rvm/gems/ruby-2.5.1/bin/i2cssh:23:in `load'
	 9: from /Users/adrian/.rvm/gems/ruby-2.5.1/gems/i2cssh-2.2.0/bin/i2cssh:298:in `<top (required)>'
	 8: from /Users/adrian/.rvm/gems/ruby-2.5.1/gems/i2cssh-2.2.0/bin/i2cssh:298:in `new'
	 7: from /Users/adrian/.rvm/gems/ruby-2.5.1/gems/i2cssh-2.2.0/lib/i2cssh.rb:26:in `initialize'
	 6: from /Users/adrian/.rvm/gems/ruby-2.5.1/gems/i2cssh-2.2.0/lib/i2cssh.rb:101:in `split_session'
	 5: from /Users/adrian/.rvm/gems/ruby-2.5.1/gems/i2cssh-2.2.0/lib/i2cssh.rb:101:in `upto'
	 4: from /Users/adrian/.rvm/gems/ruby-2.5.1/gems/i2cssh-2.2.0/lib/i2cssh.rb:102:in `block in split_session'
	 3: from /Users/adrian/.rvm/gems/ruby-2.5.1/gems/i2cssh-2.2.0/lib/i2cssh.rb:102:in `upto'
	 2: from /Users/adrian/.rvm/gems/ruby-2.5.1/gems/i2cssh-2.2.0/lib/i2cssh.rb:103:in `block (2 levels) in split_session'
	 1: from /Users/adrian/.rvm/gems/ruby-2.5.1/gems/rb-scpt-1.0.3/lib/rb-scpt.rb:642:in `method_missing'
/Users/adrian/.rvm/gems/ruby-2.5.1/gems/rb-scpt-1.0.3/lib/rb-scpt.rb:542:in `_send_command': CommandError (Appscript::CommandError)
		OSERROR: -1743
		COMMAND: app("/System/Library/CoreServices/System Events.app").processes["iTerm2"].menu_bars[1].menu_bar_items["Window"].menus["Window"].menu_items["Select Split Pane"].menus["Select Split Pane"].menu_items["Select Pane Above"].click()
```

**Comment by adrianthedev** [comment]
I still think it's a iTerm issue. I had to bump to Build 3.2.1beta4 for it to work with Mojave beta. It was then that I realised that it broke i2cssh.

**Comment by whoiskevin** [comment]
Same here. Build 3.2.1beta6 and i2cssh is broken.

i2cssh --?
Traceback (most recent call last):
	2: from /usr/local/bin/i2cssh:23:in `<main>'
	1: from /usr/local/bin/i2cssh:23:in `load'
/usr/local/lib/ruby/gems/2.5.0/gems/i2cssh-2.2.0/bin/i2cssh:229:in `<top (required)>': invalid option: --? (OptionParser::InvalidOption)

**Comment by yohoc** [comment]
same here. 
ruby 2.5.1p57 
Traceback (most recent call last):
	11: from /Users/yohoc/.rvm/gems/ruby-2.4.1/bin/i2cssh:23:in `<main>'
	10: from /Users/yohoc/.rvm/gems/ruby-2.4.1/bin/i2cssh:23:in `load'
	 9: from /Users/yohoc/.rvm/gems/ruby-2.4.1/gems/i2cssh-2.2.0/bin/i2cssh:298:in `<top (required)>'
	 8: from /Users/yohoc/.rvm/gems/ruby-2.4.1/gems/i2cssh-2.2.0/bin/i2cssh:298:in `new'
	 7: from /Users/yohoc/.rvm/gems/ruby-2.4.1/gems/i2cssh-2.2.0/lib/i2cssh.rb:26:in `initialize'
	 6: from /Users/yohoc/.rvm/gems/ruby-2.4.1/gems/i2cssh-2.2.0/lib/i2cssh.rb:101:in `split_session'
	 5: from /Users/yohoc/.rvm/gems/ruby-2.4.1/gems/i2cssh-2.2.0/lib/i2cssh.rb:101:in `upto'
	 4: from /Users/yohoc/.rvm/gems/ruby-2.4.1/gems/i2cssh-2.2.0/lib/i2cssh.rb:102:in `block in split_session'
	 3: from /Users/yohoc/.rvm/gems/ruby-2.4.1/gems/i2cssh-2.2.0/lib/i2cssh.rb:102:in `upto'
	 2: from /Users/yohoc/.rvm/gems/ruby-2.4.1/gems/i2cssh-2.2.0/lib/i2cssh.rb:103:in `block (2 levels) in split_session'
	 1: from /Users/yohoc/.rvm/gems/ruby-2.4.1/gems/rb-scpt-1.0.3/lib/rb-scpt.rb:642:in `method_missing'
/Users/yohoc/.rvm/gems/ruby-2.4.1/gems/rb-scpt-1.0.3/lib/rb-scpt.rb:542:in `_send_command': CommandError (Appscript::CommandError)
		OSERROR: -1743
		COMMAND: app("/System/Library/CoreServices/System Events.app").processes["iTerm2"].menu_bars[1].menu_bar_items["Window"].menus["Window"].menu_items["Select Split Pane"].menus["Select Split Pane"].menu_items["Select Pane Left"].click()

**Comment by yohoc** [comment]
This worked for me
 
1. Open the iterm2's plist file is Xcode
2. add row (from right click context menu)
3. in ‘key’ column select ‘Privacy - AppleEvents Sending Usage Description’ from the drop down menu (you need to scroll down)
4. restart iterm2 app.

**Comment by zivagolee** [comment]
hmm, i'm not sure how to apply @yohoc's changes. I already have this key in my info.plist.. do I replace it with the new value?

**Comment by nynhex** [comment]
@zivagolee You have to edit the plist file inside of Xcode (latest build) natively, or you can use a free plist editor, but sometimes they introduce artifacts.

**Comment by yohoc** [comment]
> hmm, i'm not sure how to apply @yohoc's changes. I already have this key in my info.plist.. do I replace it with the new value?

Just use the latest version of iterm2，it fixed the problem.
changelog:
```
- Add usage descriptions so programs running
  within iTerm2 that use the camera, contacts,
  location, the microphone, or contacts can
  request permission to do so.
```

**Comment by zivagolee** [comment]
@yohoc hmm, that is what I thought. I still have issues with using i2cssh, however...

**Comment by sysadmin1234** [comment]
@zivagolee Try downloading the test version of iterm2.  It worked for me. I was having the same issue as you.  I noticed when I launched i2cssh in terminal, it would prompt me to grant control to accessibility in Privacy, but not in iterm2, even though I've reinstalled iterm2. The latest test version did prompt me and worked after that.

**Comment by dwtien** [comment]
@zivagolee Try downloading the test version of iterm2.  It worked for me. I was having the same issue as you.  I noticed when I launched i2cssh in terminal, it would prompt me to grant control to accessibility in Privacy, but not in iterm2, even though I've reinstalled iterm2. The latest test version did prompt me and worked after that.

**Comment by zivagolee** [comment]
@dwtien nice, that worked. I deleted the app from Applications, then got the test version and unzipped it. Ran the iTerm application, then i2cssh and it finally prompted me.

**Comment by batic** [comment]
That worked for me as well, thanks.

Is there any way to send same command to all the nodes at the same time?

**Comment by RedBaron80** [comment]
Yes @batic, use broadcast mode

**Comment by batic** [comment]
Yes, I've been using that for a while now, thanks.

**Comment by youngkin** [comment]
I'm seeing this exact problem with build 3.3.0beta15 (upgraded from3.3.0beta10). I downgraded back to beta10 and it's working again.

**Comment by AkashBabu** [comment]
For those who are still facing issue, please run the following command:
> sudo gem install i2cssh

**Comment by bungandy** [comment]
Open **System Preferences** > **Security & Privacy**
under **Accessibility**, checked (enable) / Allow for iTerm

![Screen Shot 2020-03-23 at 16 32 33](https://user-images.githubusercontent.com/290786/77302450-ec105e00-6d23-11ea-8f97-97c6970d7698.png)
