### ISSUE TITLE
i2cssh fails on mojave when trying to ssh more than 2 ip

### ISSUE THREAD

**Issue by ashhar24** [wouterdebie/i2cssh#87]
Below is the error message 

> Traceback (most recent call last):
	13: from /Users/ashhar.jawaid/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `<main>'
	12: from /Users/ashhar.jawaid/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `eval'
	11: from /Users/ashhar.jawaid/.rvm/gems/ruby-2.5.1/bin/i2cssh:23:in `<main>'
	10: from /Users/ashhar.jawaid/.rvm/gems/ruby-2.5.1/bin/i2cssh:23:in `load'
	 9: from /Users/ashhar.jawaid/.rvm/gems/ruby-2.5.1/gems/i2cssh-2.2.0/bin/i2cssh:298:in `<top (required)>'
	 8: from /Users/ashhar.jawaid/.rvm/gems/ruby-2.5.1/gems/i2cssh-2.2.0/bin/i2cssh:298:in `new'
	 7: from /Users/ashhar.jawaid/.rvm/gems/ruby-2.5.1/gems/i2cssh-2.2.0/lib/i2cssh.rb:26:in `initialize'
	 6: from /Users/ashhar.jawaid/.rvm/gems/ruby-2.5.1/gems/i2cssh-2.2.0/lib/i2cssh.rb:101:in `split_session'
	 5: from /Users/ashhar.jawaid/.rvm/gems/ruby-2.5.1/gems/i2cssh-2.2.0/lib/i2cssh.rb:101:in `upto'
	 4: from /Users/ashhar.jawaid/.rvm/gems/ruby-2.5.1/gems/i2cssh-2.2.0/lib/i2cssh.rb:102:in `block in split_session'
	 3: from /Users/ashhar.jawaid/.rvm/gems/ruby-2.5.1/gems/i2cssh-2.2.0/lib/i2cssh.rb:102:in `upto'
	 2: from /Users/ashhar.jawaid/.rvm/gems/ruby-2.5.1/gems/i2cssh-2.2.0/lib/i2cssh.rb:103:in `block (2 levels) in split_session'
	 1: from /Users/ashhar.jawaid/.rvm/gems/ruby-2.5.1/gems/rb-scpt-1.0.3/lib/rb-scpt.rb:642:in `method_missing'
/Users/ashhar.jawaid/.rvm/gems/ruby-2.5.1/gems/rb-scpt-1.0.3/lib/rb-scpt.rb:542:in `_send_command': CommandError (Appscript::CommandError)
		OSERROR: -1743
		COMMAND: app("/System/Library/CoreServices/System Events.app").processes["iTerm2"].menu_bars[1].menu_bar_items["Window"].menus["Window"].menu_items["Select Split Pane"].menus["Select Split Pane"].menu_items["Select Pane Left"].click()

**Comment by billywatson** [comment]
👍 +1

**Comment by Vijendra07Kulhade** [comment]
Same error when running this on Mac Mojave
`i2cssh -m kafka@ip,kafka@ip`
```/Library/Ruby/Gems/2.3.0/gems/rb-scpt-1.0.3/lib/rb-scpt.rb:177:in `block in pack': Unknown Keyword: :terminal (IndexError)
	from /Library/Ruby/Gems/2.3.0/gems/rb-scpt-1.0.3/lib/rb-scpt.rb:177:in `fetch'
	from /Library/Ruby/Gems/2.3.0/gems/rb-scpt-1.0.3/lib/rb-scpt.rb:177:in `pack'
	from /Library/Ruby/Gems/2.3.0/gems/rb-scpt-1.0.3/lib/_aem/send.rb:37:in `block in initialize'
	from /Library/Ruby/Gems/2.3.0/gems/rb-scpt-1.0.3/lib/_aem/send.rb:37:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/rb-scpt-1.0.3/lib/_aem/send.rb:37:in `initialize'
	from /Library/Ruby/Gems/2.3.0/gems/rb-scpt-1.0.3/lib/aem.rb:218:in `new'
	from /Library/Ruby/Gems/2.3.0/gems/rb-scpt-1.0.3/lib/aem.rb:218:in `event'
	from /Library/Ruby/Gems/2.3.0/gems/rb-scpt-1.0.3/lib/rb-scpt.rb:506:in `_send_command'
	from /Library/Ruby/Gems/2.3.0/gems/rb-scpt-1.0.3/lib/rb-scpt.rb:642:in `method_missing'
	from /Library/Ruby/Gems/2.3.0/gems/i2cssh-1.16.0/lib/i2cssh.rb:19:in `initialize'
	from /Library/Ruby/Gems/2.3.0/gems/i2cssh-1.16.0/bin/i2cssh:298:in `new'
	from /Library/Ruby/Gems/2.3.0/gems/i2cssh-1.16.0/bin/i2cssh:298:in `<top (required)>'
	from /usr/local/bin/i2cssh:22:in `load'
	from /usr/local/bin/i2cssh:22:in `<main>'```

**Comment by dx7** [comment]
I'd had problems using "-m" options too. I've fixed that with #78 . I'm using Mojave right now without problems.

**Comment by wouterdebie** [comment]
I just moved to a python version. This should solve a bunch of issues. Please check it out.
